/** @type {import('next').NextConfig} */
const nextConfig = {
  // Optimized for SEO and performance
  reactStrictMode: true,
  
  // Image optimization
  images: {
    formats: ['image/avif', 'image/webp'],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },

  // Compression
  compress: true,

  // Power optimizations
  poweredByHeader: false,

  // Trailing slashes for SEO
  trailingSlash: false,

  // MULTILINGUAL INDEXATION FREEZE
  // Block /en/* and /ru/* from indexing via X-Robots-Tag headers
  // These pages contain broken Spanish content
  async redirects() {
    return [
      // --- SEO commercial-layer cleanup (Sep 2026) ---
      // District-level pages (service+city+district) removed: GSC showed 77% of
      // 180 pages had zero impressions in 140 days; DataForSEO confirmed near-zero
      // real search volume for "{service} {district} {city}" phrasing. Consolidated
      // into the parent service+city page to fix diluted/cannibalized ranking signal.
      { source: '/fontanero/madrid/centro', destination: '/fontanero/madrid', permanent: true },
      { source: '/fontanero/madrid/salamanca', destination: '/fontanero/madrid', permanent: true },
      { source: '/fontanero/madrid/chamberi', destination: '/fontanero/madrid', permanent: true },
      { source: '/fontanero/madrid/retiro', destination: '/fontanero/madrid', permanent: true },
      { source: '/fontanero/madrid/chamartin', destination: '/fontanero/madrid', permanent: true },
      { source: '/fontanero/barcelona/ciutat-vella', destination: '/fontanero/barcelona', permanent: true },
      { source: '/fontanero/barcelona/eixample', destination: '/fontanero/barcelona', permanent: true },
      { source: '/fontanero/barcelona/gracia', destination: '/fontanero/barcelona', permanent: true },
      { source: '/fontanero/barcelona/sants', destination: '/fontanero/barcelona', permanent: true },
      { source: '/fontanero/barcelona/sarria', destination: '/fontanero/barcelona', permanent: true },
      { source: '/fontanero/valencia/ciutat-vella', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/valencia/leixample', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/valencia/extramurs', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/valencia/campanar', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/valencia/poblats-maritims', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/sevilla/casco-antiguo', destination: '/fontanero/sevilla', permanent: true },
      { source: '/fontanero/sevilla/triana', destination: '/fontanero/sevilla', permanent: true },
      { source: '/fontanero/sevilla/nervion', destination: '/fontanero/sevilla', permanent: true },
      { source: '/fontanero/sevilla/macarena', destination: '/fontanero/sevilla', permanent: true },
      { source: '/fontanero/sevilla/sur', destination: '/fontanero/sevilla', permanent: true },
      { source: '/fontanero/zaragoza/centro', destination: '/fontanero/zaragoza', permanent: true },
      { source: '/fontanero/zaragoza/delicias', destination: '/fontanero/zaragoza', permanent: true },
      { source: '/fontanero/zaragoza/universidad', destination: '/fontanero/zaragoza', permanent: true },
      { source: '/fontanero/zaragoza/san-jose', destination: '/fontanero/zaragoza', permanent: true },
      { source: '/fontanero/zaragoza/actur', destination: '/fontanero/zaragoza', permanent: true },
      { source: '/fontanero/malaga/centro', destination: '/fontanero/malaga', permanent: true },
      { source: '/fontanero/malaga/este', destination: '/fontanero/malaga', permanent: true },
      { source: '/fontanero/malaga/ciudad-jardin', destination: '/fontanero/malaga', permanent: true },
      { source: '/fontanero/malaga/teatinos', destination: '/fontanero/malaga', permanent: true },
      { source: '/fontanero/malaga/carretera-cadiz', destination: '/fontanero/malaga', permanent: true },
      { source: '/electricista/madrid/centro', destination: '/electricista/madrid', permanent: true },
      { source: '/electricista/madrid/salamanca', destination: '/electricista/madrid', permanent: true },
      { source: '/electricista/madrid/chamberi', destination: '/electricista/madrid', permanent: true },
      { source: '/electricista/madrid/retiro', destination: '/electricista/madrid', permanent: true },
      { source: '/electricista/madrid/chamartin', destination: '/electricista/madrid', permanent: true },
      { source: '/electricista/barcelona/ciutat-vella', destination: '/electricista/barcelona', permanent: true },
      { source: '/electricista/barcelona/eixample', destination: '/electricista/barcelona', permanent: true },
      { source: '/electricista/barcelona/gracia', destination: '/electricista/barcelona', permanent: true },
      { source: '/electricista/barcelona/sants', destination: '/electricista/barcelona', permanent: true },
      { source: '/electricista/barcelona/sarria', destination: '/electricista/barcelona', permanent: true },
      { source: '/electricista/valencia/ciutat-vella', destination: '/electricista/valencia', permanent: true },
      { source: '/electricista/valencia/leixample', destination: '/electricista/valencia', permanent: true },
      { source: '/electricista/valencia/extramurs', destination: '/electricista/valencia', permanent: true },
      { source: '/electricista/valencia/campanar', destination: '/electricista/valencia', permanent: true },
      { source: '/electricista/valencia/poblats-maritims', destination: '/electricista/valencia', permanent: true },
      { source: '/electricista/sevilla/casco-antiguo', destination: '/electricista/sevilla', permanent: true },
      { source: '/electricista/sevilla/triana', destination: '/electricista/sevilla', permanent: true },
      { source: '/electricista/sevilla/nervion', destination: '/electricista/sevilla', permanent: true },
      { source: '/electricista/sevilla/macarena', destination: '/electricista/sevilla', permanent: true },
      { source: '/electricista/sevilla/sur', destination: '/electricista/sevilla', permanent: true },
      { source: '/electricista/zaragoza/centro', destination: '/electricista/zaragoza', permanent: true },
      { source: '/electricista/zaragoza/delicias', destination: '/electricista/zaragoza', permanent: true },
      { source: '/electricista/zaragoza/universidad', destination: '/electricista/zaragoza', permanent: true },
      { source: '/electricista/zaragoza/san-jose', destination: '/electricista/zaragoza', permanent: true },
      { source: '/electricista/zaragoza/actur', destination: '/electricista/zaragoza', permanent: true },
      { source: '/electricista/malaga/centro', destination: '/electricista/malaga', permanent: true },
      { source: '/electricista/malaga/este', destination: '/electricista/malaga', permanent: true },
      { source: '/electricista/malaga/ciudad-jardin', destination: '/electricista/malaga', permanent: true },
      { source: '/electricista/malaga/teatinos', destination: '/electricista/malaga', permanent: true },
      { source: '/electricista/malaga/carretera-cadiz', destination: '/electricista/malaga', permanent: true },
      { source: '/desatascos/madrid/centro', destination: '/desatascos/madrid', permanent: true },
      { source: '/desatascos/madrid/salamanca', destination: '/desatascos/madrid', permanent: true },
      { source: '/desatascos/madrid/chamberi', destination: '/desatascos/madrid', permanent: true },
      { source: '/desatascos/madrid/retiro', destination: '/desatascos/madrid', permanent: true },
      { source: '/desatascos/madrid/chamartin', destination: '/desatascos/madrid', permanent: true },
      { source: '/desatascos/barcelona/ciutat-vella', destination: '/desatascos/barcelona', permanent: true },
      { source: '/desatascos/barcelona/eixample', destination: '/desatascos/barcelona', permanent: true },
      { source: '/desatascos/barcelona/gracia', destination: '/desatascos/barcelona', permanent: true },
      { source: '/desatascos/barcelona/sants', destination: '/desatascos/barcelona', permanent: true },
      { source: '/desatascos/barcelona/sarria', destination: '/desatascos/barcelona', permanent: true },
      { source: '/desatascos/valencia/ciutat-vella', destination: '/desatascos/valencia', permanent: true },
      { source: '/desatascos/valencia/leixample', destination: '/desatascos/valencia', permanent: true },
      { source: '/desatascos/valencia/extramurs', destination: '/desatascos/valencia', permanent: true },
      { source: '/desatascos/valencia/campanar', destination: '/desatascos/valencia', permanent: true },
      { source: '/desatascos/valencia/poblats-maritims', destination: '/desatascos/valencia', permanent: true },
      { source: '/desatascos/sevilla/casco-antiguo', destination: '/desatascos/sevilla', permanent: true },
      { source: '/desatascos/sevilla/triana', destination: '/desatascos/sevilla', permanent: true },
      { source: '/desatascos/sevilla/nervion', destination: '/desatascos/sevilla', permanent: true },
      { source: '/desatascos/sevilla/macarena', destination: '/desatascos/sevilla', permanent: true },
      { source: '/desatascos/sevilla/sur', destination: '/desatascos/sevilla', permanent: true },
      { source: '/desatascos/zaragoza/centro', destination: '/desatascos/zaragoza', permanent: true },
      { source: '/desatascos/zaragoza/delicias', destination: '/desatascos/zaragoza', permanent: true },
      { source: '/desatascos/zaragoza/universidad', destination: '/desatascos/zaragoza', permanent: true },
      { source: '/desatascos/zaragoza/san-jose', destination: '/desatascos/zaragoza', permanent: true },
      { source: '/desatascos/zaragoza/actur', destination: '/desatascos/zaragoza', permanent: true },
      { source: '/desatascos/malaga/centro', destination: '/desatascos/malaga', permanent: true },
      { source: '/desatascos/malaga/este', destination: '/desatascos/malaga', permanent: true },
      { source: '/desatascos/malaga/ciudad-jardin', destination: '/desatascos/malaga', permanent: true },
      { source: '/desatascos/malaga/teatinos', destination: '/desatascos/malaga', permanent: true },
      { source: '/desatascos/malaga/carretera-cadiz', destination: '/desatascos/malaga', permanent: true },
      { source: '/aire-acondicionado/madrid/centro', destination: '/aire-acondicionado/madrid', permanent: true },
      { source: '/aire-acondicionado/madrid/salamanca', destination: '/aire-acondicionado/madrid', permanent: true },
      { source: '/aire-acondicionado/madrid/chamberi', destination: '/aire-acondicionado/madrid', permanent: true },
      { source: '/aire-acondicionado/madrid/retiro', destination: '/aire-acondicionado/madrid', permanent: true },
      { source: '/aire-acondicionado/madrid/chamartin', destination: '/aire-acondicionado/madrid', permanent: true },
      { source: '/aire-acondicionado/barcelona/ciutat-vella', destination: '/aire-acondicionado/barcelona', permanent: true },
      { source: '/aire-acondicionado/barcelona/eixample', destination: '/aire-acondicionado/barcelona', permanent: true },
      { source: '/aire-acondicionado/barcelona/gracia', destination: '/aire-acondicionado/barcelona', permanent: true },
      { source: '/aire-acondicionado/barcelona/sants', destination: '/aire-acondicionado/barcelona', permanent: true },
      { source: '/aire-acondicionado/barcelona/sarria', destination: '/aire-acondicionado/barcelona', permanent: true },
      { source: '/aire-acondicionado/valencia/ciutat-vella', destination: '/aire-acondicionado/valencia', permanent: true },
      { source: '/aire-acondicionado/valencia/leixample', destination: '/aire-acondicionado/valencia', permanent: true },
      { source: '/aire-acondicionado/valencia/extramurs', destination: '/aire-acondicionado/valencia', permanent: true },
      { source: '/aire-acondicionado/valencia/campanar', destination: '/aire-acondicionado/valencia', permanent: true },
      { source: '/aire-acondicionado/valencia/poblats-maritims', destination: '/aire-acondicionado/valencia', permanent: true },
      { source: '/aire-acondicionado/sevilla/casco-antiguo', destination: '/aire-acondicionado/sevilla', permanent: true },
      { source: '/aire-acondicionado/sevilla/triana', destination: '/aire-acondicionado/sevilla', permanent: true },
      { source: '/aire-acondicionado/sevilla/nervion', destination: '/aire-acondicionado/sevilla', permanent: true },
      { source: '/aire-acondicionado/sevilla/macarena', destination: '/aire-acondicionado/sevilla', permanent: true },
      { source: '/aire-acondicionado/sevilla/sur', destination: '/aire-acondicionado/sevilla', permanent: true },
      { source: '/aire-acondicionado/zaragoza/centro', destination: '/aire-acondicionado/zaragoza', permanent: true },
      { source: '/aire-acondicionado/zaragoza/delicias', destination: '/aire-acondicionado/zaragoza', permanent: true },
      { source: '/aire-acondicionado/zaragoza/universidad', destination: '/aire-acondicionado/zaragoza', permanent: true },
      { source: '/aire-acondicionado/zaragoza/san-jose', destination: '/aire-acondicionado/zaragoza', permanent: true },
      { source: '/aire-acondicionado/zaragoza/actur', destination: '/aire-acondicionado/zaragoza', permanent: true },
      { source: '/aire-acondicionado/malaga/centro', destination: '/aire-acondicionado/malaga', permanent: true },
      { source: '/aire-acondicionado/malaga/este', destination: '/aire-acondicionado/malaga', permanent: true },
      { source: '/aire-acondicionado/malaga/ciudad-jardin', destination: '/aire-acondicionado/malaga', permanent: true },
      { source: '/aire-acondicionado/malaga/teatinos', destination: '/aire-acondicionado/malaga', permanent: true },
      { source: '/aire-acondicionado/malaga/carretera-cadiz', destination: '/aire-acondicionado/malaga', permanent: true },
      { source: '/calefaccion/madrid/centro', destination: '/calefaccion/madrid', permanent: true },
      { source: '/calefaccion/madrid/salamanca', destination: '/calefaccion/madrid', permanent: true },
      { source: '/calefaccion/madrid/chamberi', destination: '/calefaccion/madrid', permanent: true },
      { source: '/calefaccion/madrid/retiro', destination: '/calefaccion/madrid', permanent: true },
      { source: '/calefaccion/madrid/chamartin', destination: '/calefaccion/madrid', permanent: true },
      { source: '/calefaccion/barcelona/ciutat-vella', destination: '/calefaccion/barcelona', permanent: true },
      { source: '/calefaccion/barcelona/eixample', destination: '/calefaccion/barcelona', permanent: true },
      { source: '/calefaccion/barcelona/gracia', destination: '/calefaccion/barcelona', permanent: true },
      { source: '/calefaccion/barcelona/sants', destination: '/calefaccion/barcelona', permanent: true },
      { source: '/calefaccion/barcelona/sarria', destination: '/calefaccion/barcelona', permanent: true },
      { source: '/calefaccion/valencia/ciutat-vella', destination: '/calefaccion/valencia', permanent: true },
      { source: '/calefaccion/valencia/leixample', destination: '/calefaccion/valencia', permanent: true },
      { source: '/calefaccion/valencia/extramurs', destination: '/calefaccion/valencia', permanent: true },
      { source: '/calefaccion/valencia/campanar', destination: '/calefaccion/valencia', permanent: true },
      { source: '/calefaccion/valencia/poblats-maritims', destination: '/calefaccion/valencia', permanent: true },
      { source: '/calefaccion/sevilla/casco-antiguo', destination: '/calefaccion/sevilla', permanent: true },
      { source: '/calefaccion/sevilla/triana', destination: '/calefaccion/sevilla', permanent: true },
      { source: '/calefaccion/sevilla/nervion', destination: '/calefaccion/sevilla', permanent: true },
      { source: '/calefaccion/sevilla/macarena', destination: '/calefaccion/sevilla', permanent: true },
      { source: '/calefaccion/sevilla/sur', destination: '/calefaccion/sevilla', permanent: true },
      { source: '/calefaccion/zaragoza/centro', destination: '/calefaccion/zaragoza', permanent: true },
      { source: '/calefaccion/zaragoza/delicias', destination: '/calefaccion/zaragoza', permanent: true },
      { source: '/calefaccion/zaragoza/universidad', destination: '/calefaccion/zaragoza', permanent: true },
      { source: '/calefaccion/zaragoza/san-jose', destination: '/calefaccion/zaragoza', permanent: true },
      { source: '/calefaccion/zaragoza/actur', destination: '/calefaccion/zaragoza', permanent: true },
      { source: '/calefaccion/malaga/centro', destination: '/calefaccion/malaga', permanent: true },
      { source: '/calefaccion/malaga/este', destination: '/calefaccion/malaga', permanent: true },
      { source: '/calefaccion/malaga/ciudad-jardin', destination: '/calefaccion/malaga', permanent: true },
      { source: '/calefaccion/malaga/teatinos', destination: '/calefaccion/malaga', permanent: true },
      { source: '/calefaccion/malaga/carretera-cadiz', destination: '/calefaccion/malaga', permanent: true },
      { source: '/limpieza-tuberias/madrid/centro', destination: '/limpieza-tuberias/madrid', permanent: true },
      { source: '/limpieza-tuberias/madrid/salamanca', destination: '/limpieza-tuberias/madrid', permanent: true },
      { source: '/limpieza-tuberias/madrid/chamberi', destination: '/limpieza-tuberias/madrid', permanent: true },
      { source: '/limpieza-tuberias/madrid/retiro', destination: '/limpieza-tuberias/madrid', permanent: true },
      { source: '/limpieza-tuberias/madrid/chamartin', destination: '/limpieza-tuberias/madrid', permanent: true },
      { source: '/limpieza-tuberias/barcelona/ciutat-vella', destination: '/limpieza-tuberias/barcelona', permanent: true },
      { source: '/limpieza-tuberias/barcelona/eixample', destination: '/limpieza-tuberias/barcelona', permanent: true },
      { source: '/limpieza-tuberias/barcelona/gracia', destination: '/limpieza-tuberias/barcelona', permanent: true },
      { source: '/limpieza-tuberias/barcelona/sants', destination: '/limpieza-tuberias/barcelona', permanent: true },
      { source: '/limpieza-tuberias/barcelona/sarria', destination: '/limpieza-tuberias/barcelona', permanent: true },
      { source: '/limpieza-tuberias/valencia/ciutat-vella', destination: '/limpieza-tuberias/valencia', permanent: true },
      { source: '/limpieza-tuberias/valencia/leixample', destination: '/limpieza-tuberias/valencia', permanent: true },
      { source: '/limpieza-tuberias/valencia/extramurs', destination: '/limpieza-tuberias/valencia', permanent: true },
      { source: '/limpieza-tuberias/valencia/campanar', destination: '/limpieza-tuberias/valencia', permanent: true },
      { source: '/limpieza-tuberias/valencia/poblats-maritims', destination: '/limpieza-tuberias/valencia', permanent: true },
      { source: '/limpieza-tuberias/sevilla/casco-antiguo', destination: '/limpieza-tuberias/sevilla', permanent: true },
      { source: '/limpieza-tuberias/sevilla/triana', destination: '/limpieza-tuberias/sevilla', permanent: true },
      { source: '/limpieza-tuberias/sevilla/nervion', destination: '/limpieza-tuberias/sevilla', permanent: true },
      { source: '/limpieza-tuberias/sevilla/macarena', destination: '/limpieza-tuberias/sevilla', permanent: true },
      { source: '/limpieza-tuberias/sevilla/sur', destination: '/limpieza-tuberias/sevilla', permanent: true },
      { source: '/limpieza-tuberias/zaragoza/centro', destination: '/limpieza-tuberias/zaragoza', permanent: true },
      { source: '/limpieza-tuberias/zaragoza/delicias', destination: '/limpieza-tuberias/zaragoza', permanent: true },
      { source: '/limpieza-tuberias/zaragoza/universidad', destination: '/limpieza-tuberias/zaragoza', permanent: true },
      { source: '/limpieza-tuberias/zaragoza/san-jose', destination: '/limpieza-tuberias/zaragoza', permanent: true },
      { source: '/limpieza-tuberias/zaragoza/actur', destination: '/limpieza-tuberias/zaragoza', permanent: true },
      { source: '/limpieza-tuberias/malaga/centro', destination: '/limpieza-tuberias/malaga', permanent: true },
      { source: '/limpieza-tuberias/malaga/este', destination: '/limpieza-tuberias/malaga', permanent: true },
      { source: '/limpieza-tuberias/malaga/ciudad-jardin', destination: '/limpieza-tuberias/malaga', permanent: true },
      { source: '/limpieza-tuberias/malaga/teatinos', destination: '/limpieza-tuberias/malaga', permanent: true },
      { source: '/limpieza-tuberias/malaga/carretera-cadiz', destination: '/limpieza-tuberias/malaga', permanent: true },

      // Orphan URLs with real GSC impressions pointing at removed content
      // (old blog posts and per-service problem pages no longer in the codebase).
      // Redirected to the most relevant existing commercial page instead of 404.
      { source: '/fontanero/desatascos', destination: '/desatascos', permanent: true },
      { source: '/fontanero/instalacion-cambio-inodoros', destination: '/fontanero/instalaciones', permanent: true },
      { source: '/fontanero/instalacion-lavabos', destination: '/fontanero/instalaciones', permanent: true },
      { source: '/blog/fontaneria/calentador-gas-no-enciende', destination: '/fontanero/calentadores-termos', permanent: true },
      { source: '/blog/fontaneria/como-vaciar-termo-electrico', destination: '/fontanero/calentadores-termos', permanent: true },
      { source: '/blog/fontaneria/que-hacer-fuga-agua-casa', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/cuanto-cuesta-fontanero-valencia', destination: '/fontanero/valencia', permanent: true },
      { source: '/fontanero/descalcificadores-osmosis', destination: '/fontanero', permanent: true },
      { source: '/fontanero/bajantes', destination: '/limpieza-tuberias', permanent: true },
      { source: '/fontanero/mamparas-ducha', destination: '/fontanero', permanent: true },
      { source: '/fontanero/grupos-presion-agua', destination: '/fontanero', permanent: true },
      { source: '/fontanero/cambio-reparacion-grifos', destination: '/fontanero/instalaciones', permanent: true },
      { source: '/fontanero/reparacion-duchas', destination: '/fontanero', permanent: true },
      { source: '/fontanero/reparacion-cisternas', destination: '/fontanero', permanent: true },
      { source: '/fontanero/cambio-banera-por-ducha', destination: '/fontanero', permanent: true },
      // These map to /reparacion-fugas (not the generic hub) because GSC query data
      // shows real "cisterna/grifo gotea" (leak) intent, incl. the highest-traffic
      // orphan URL on the site (2093 impressions / 44 clicks).
      { source: '/blog/fontaneria/por-que-gotea-cisterna', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/como-arreglar-grifo-que-gotea', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/por-que-cisterna-gotea-detectarlo', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/por-que-gotea-un-grifo-cerrado', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/que-fuga-agua-casa', destination: '/fontanero/reparacion-fugas', permanent: true },
      { source: '/blog/fontaneria/como-cambiar-el-grifo-de-la-cocina', destination: '/fontanero/instalaciones', permanent: true },
      { source: '/electricista/cargador-coche-electrico', destination: '/electricista', permanent: true },
      { source: '/electricista/averias-electricas', destination: '/electricista', permanent: true },
      { source: '/electricista/urgencias-electricas', destination: '/electricista', permanent: true },
      { source: '/electricista/cuadros-electricos', destination: '/electricista', permanent: true },
      { source: '/electricista/iluminacion-led', destination: '/electricista', permanent: true },
      { source: '/electricista/pequenos-trabajos-electricos', destination: '/electricista', permanent: true },
      { source: '/electricista/enchufes-interruptores', destination: '/electricista', permanent: true },
      { source: '/electricista/instalaciones-electricas', destination: '/electricista', permanent: true },
      { source: '/electricista/revision-electrica', destination: '/electricista', permanent: true },
      { source: '/electricista/mantenimiento-electrico', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/instalar-ventilador-techo-con-luz', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/que-hacer-cortocircuito-casa', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/que-her-cortocircuito-casa', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/que-reparar24-cortocircuito-casa', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/como-cambiar-un-tubo-fluorescente-por-uno-led', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/como-poner-lampara-de-techo', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/cuanto-cuesta-electricista-valencia', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/por-que-salta-el-diferencial-al-encender-un-aparato', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/como-cambiar-enchufe', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/por-que-salta-diferencial', destination: '/electricista', permanent: true },
      { source: '/blog/electricidad/que-herramientas-necesita-un-electricista', destination: '/electricista', permanent: true },
      { source: '/desatascos/camion-cuba', destination: '/desatascos', permanent: true },
      { source: '/desatascos/desatascar-fregadero', destination: '/desatascos', permanent: true },
      { source: '/desatascos/desatasco-tuberias', destination: '/desatascos', permanent: true },
      { source: '/desatascos/limpieza-fosas-septicas', destination: '/desatascos', permanent: true },
      { source: '/desatascos/desatascar-wc', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/como-desatascar-fregadero', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/como-saber-tuberia-atascada', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/por-que-se-atasca-el-fregadero-cada-poco', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/por-que-se-atasca-fregadero-cada-poco', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/como-desatascar-ducha', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/como-desatascar-lavabo', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/cuando-llamar-camion-cuba', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/que-hacer-wc-atascado', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos/vaciado-fosa-septica-precio', destination: '/desatascos', permanent: true },
      { source: '/blog/desatascos', destination: '/desatascos', permanent: true },
      { source: '/aire-acondicionado/limpieza-conductos-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/mantenimiento-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/instalacion-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/carga-gas-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/preinstalacion-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/reparacion-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/aire-acondicionado-cassette-techo', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/empresa-climatizacion', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/instalacion-split', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/aire-acondicionado-conductos', destination: '/aire-acondicionado', permanent: true },
      { source: '/aire-acondicionado/bomba-calor', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/aire-acondicionado-no-enciende', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/por-que-el-aire-acondicionado-gotea-dentro-de-casa', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/cuanto-cuesta-instalar-split', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/cuanto-cuesta-instalar-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/cuando-hacer-mantenimiento-aire-acondicionado', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion/aire-acondicionado-con-bomba-de-calor', destination: '/aire-acondicionado', permanent: true },
      { source: '/blog/climatizacion', destination: '/aire-acondicionado', permanent: true },
      { source: '/calefaccion/suelo-radiante', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/instalacion-calefaccion', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/reparacion-calderas', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/mantenimiento-calderas', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/calefaccion-central-comunidades', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/radiadores-calefaccion', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/aerotermia-calefaccion', destination: '/calefaccion', permanent: true },
      { source: '/calefaccion/termostatos-valvulas', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/por-que-baja-la-presion-de-la-caldera-cada-poco', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/caldera-no-arranca-que-revisar', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/como-purgar-radiadores', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/aerotermia-precio', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/aerotermia-con-radiadores', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion/presion-baja-caldera', destination: '/calefaccion', permanent: true },
      { source: '/blog/calefaccion', destination: '/calefaccion', permanent: true },
      { source: '/limpieza-tuberias/inspeccion-camara-tuberias', destination: '/limpieza-tuberias', permanent: true },
      { source: '/limpieza-tuberias/limpieza-bajantes', destination: '/limpieza-tuberias', permanent: true },
      { source: '/limpieza-tuberias/limpieza-alta-presion-camion-cuba', destination: '/limpieza-tuberias', permanent: true },
      { source: '/limpieza-tuberias/limpieza-tuberias-empresas', destination: '/limpieza-tuberias', permanent: true },
      { source: '/limpieza-tuberias/limpieza-tuberias-comunidades', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/limpieza-arquetas-olores-comunidad', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/bicarbonato-y-vinagre-para-desatascar', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/como-limpiar-tuberias-casa', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/atascos-repetidos-en-tuberias-despues-de-desatascar', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/inspeccion-camara-tuberias-cuando-conviene', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/precio-limpieza-cal-tuberias', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/como-limpiar-las-tuberias-de-agua', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento/cuando-limpiar-bajantes-comunidad', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog/saneamiento', destination: '/limpieza-tuberias', permanent: true },
      { source: '/blog', destination: '/', permanent: true },
    ]
  },
  async headers() {
    return [
      {
        source: '/en/:path*',
        headers: [
          {
            key: 'X-Robots-Tag',
            value: 'noindex, nofollow, noarchive, nosnippet',
          },
        ],
      },
      {
        source: '/ru/:path*',
        headers: [
          {
            key: 'X-Robots-Tag',
            value: 'noindex, nofollow, noarchive, nosnippet',
          },
        ],
      },
    ]
  },
}

module.exports = nextConfig
